baseURL = "https://un-ricard-sinon-rien.io"
title = "Un RICard sinon rien"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = "compose"
themesDir = "./themes/"

enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Avant Propos"
    weight = 2
    url = "/docs/avant-propos/"

[[menu.main]]
    name = "Travaux en cours"
    weight = 6
    url = "/docs/travaux-en-cours/"

[[menu.main]]
    name = "Qu'est-ce que le RIC?"
    weight = 5
    url = "/docs/le-ric-kezako"

[[menu.main]]
    name = "La Matrice"
    weight = 3
    url = "/docs/matrice-de-comparaison/"


[[menu.main]]
    name = "Actu & Evènements"
    weight = 4
    url = "/docs/actus-evenements/"





[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# Everything below this are Site Params

[params]

  repo = "https://github.com/ricard-io/setup-website"

  time_format_blog = "Monday, January 02, 2020"
  time_format_default = "January 2, 2020"
  enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

  # Site logo
  [params.logo]
    lightMode = "ric_carl_blue_green.png"
    darkMode = "ric_carl_blue_green.png"

  [params.source]
    name = "Ce travail, sur GitHub"
    icon = "github.svg"
    url = "https://github.com/ricard-io/setup-website"

  # optional
  # attribution. Feel free to delete this
  # [params.author]
    # name = "Jean-Baptiste Lasselle"
    # url = "https://github.com/Jean-Baptiste-Lasselle"
