version: "3.7"

services:
  hugo_cms:
    # we need extended, and nodejs for sass!
    image: quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}
    container_name: hugo_cms
    build:
       context: .
       dockerfile: cms.Dockerfile
       args:
         - ALPINE_OCI_IMAGE_TAG=${ALPINE_OCI_IMAGE_TAG}
         - GOLANG_VERSION=${GOLANG_VERSION}
         - HUGO_VERSION=${HUGO_VERSION}
         - GIT_COMMIT_ID=${GIT_COMMIT_ID}
         - CICD_BUILD_ID=${CICD_BUILD_ID}
         - CICD_BUILD_TIMESTAMP=${CICD_BUILD_TIMESTAMP}
         - QUAY_OCI_IMAGE_TAG=${QUAY_OCI_IMAGE_TAG}
    env_file:
      - ./.cms.env
  hugo_heroku:
    image: quay.io/ricardio/website:${QUAY_OCI_IMAGE_TAG}
    container_name: hugo_heroku
    build:
       context: .
       dockerfile: heroku.Dockerfile
       args:
         - HTTPD_OCI_IMAGE_TAG=${HTTPD_OCI_IMAGE_TAG}
         - ALPINE_OCI_IMAGE_TAG=${ALPINE_OCI_IMAGE_TAG}
         - GOLANG_VERSION=${GOLANG_VERSION}
         - HUGO_VERSION=${HUGO_VERSION}
         - HUGO_BASE_URL=${HUGO_BASE_URL}
         - GIT_COMMIT_ID=${GIT_COMMIT_ID}
         - CICD_BUILD_ID=${CICD_BUILD_ID}
         - CICD_BUILD_TIMESTAMP=${CICD_BUILD_TIMESTAMP}
    env_file:
      - ./.heroku.env
