version: 2.1

parameters:
  secrethub_org:
    type: string
    default: "ric1718"
    description: "SecretHub Org to use to fetch secrets ?"
  secrethub_repo:
    type: string
    default: "cicd"
    description: "SecretHub Repo to use to fetch secrets ?"

orbs:
  heroku: circleci/heroku@1.2.3
  docker: circleci/docker@1.5
  secrethub: secrethub/cli@1.0.0
jobs:
  container_images_publish:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    environment:
      SECRETHUB_ORG: << pipeline.parameters.secrethub_org >>
      SECRETHUB_REPO: << pipeline.parameters.secrethub_repo >>
    steps:
      - checkout
      - secrethub/install
      - docker/install-docker-compose
      - run:
          command: |
                    echo "Checking Circle CI Job env. variables"
                    echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
                    echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
                    export GIT_RELEASE_TAG=$(git describe --tags --abbrev=0)
                    export QUAY_OCI_IMAGE_TAG=${GIT_RELEASE_TAG}-heroku
                    echo "QUAY_OCI_IMAGE_TAG=[${QUAY_OCI_IMAGE_TAG}]"
                    export GIT_COMMIT_ID=$(git rev-parse --short HEAD)
                    docker-compose build hugo_heroku
          name: "Container images build: Hugo Build (checking no hugo build error occurs)"
      - run:
          command: |
                    echo "Checking Circle CI Job env. variables"
                    echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
                    echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
                    QUAY_BOT_USERNAME=$(secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/carlbot/oci/quay-io/user-name)
                    QUAY_BOT_SECRET=$(secrethub read ${SECRETHUB_ORG}/${SECRETHUB_REPO}/carlbot/oci/quay-io/user-pwd)
                    echo "QUAY_BOT_USERNAME=[${QUAY_BOT_USERNAME}]"
                    # echo "QUAY_BOT_SECRET=[${QUAY_BOT_SECRET}]"
                    docker login -u="${QUAY_BOT_USERNAME}" -p="${QUAY_BOT_SECRET}" quay.io
                    export GIT_RELEASE_TAG=$(git describe --tags --abbrev=0)
                    export QUAY_OCI_IMAGE_TAG=${GIT_RELEASE_TAG}-heroku
                    docker tag "quay.io/ric1718/une_proposition:${QUAY_OCI_IMAGE_TAG}" "quay.io/ric1718/une_proposition:stable-latest"
                    echo "checking [date time] (sometimes data time in Circle CI pipelines is wrong, so that Container registry rejects the [docker push]...)"
                    echo "date time in Circle CI Pipeline is [$(date)] "
                    date
                    docker push "quay.io/ric1718/une_proposition:${QUAY_OCI_IMAGE_TAG}"
                    docker push "quay.io/ric1718/une_proposition:stable-latest"
          name: "Container images publish to quay.io"

  deploy_to_heroku:
    machine:
      image: 'ubuntu-1604:201903-01'
      resource_class: medium
    environment:
      SECRETHUB_ORG: << pipeline.parameters.secrethub_org >>
      SECRETHUB_REPO: << pipeline.parameters.secrethub_repo >>
      HEROKU_APP_ID: ric-carl
    steps:
      - checkout
      - secrethub/install
      - heroku/install
      - run:
          command: |
            echo "Checking context variables from [riccarl-cicd] context"
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
            echo "HEROKU_APP_ID=[${HEROKU_APP_ID}]"
          name: "Deploy to heroku as https://ric-carl.herokuapp.com/ "
      - run:
          name: "Heroku Check Authentication"
          command: |
            echo "Checking Heroku Authentication is successful, with the secrethub provided Heroku API Token"
            export HEROKU_API_KEY=$(secrethub read "${SECRETHUB_ORG}/${SECRETHUB_REPO}/carlbot/heroku/api-token")
            heroku auth:whoami
      - run:
          name: "Initializing Heroku Git repo and Set Heroku Stack"
          command: |
            echo "Initializing Heroku Git repo"
            export HEROKU_API_KEY=$(secrethub read "${SECRETHUB_ORG}/${SECRETHUB_REPO}/carlbot/heroku/api-token")
            heroku git:remote -a $HEROKU_APP_ID
            heroku stack:set container --app $HEROKU_APP_ID
      - run:
          name: "Deploy to Heroku via Git, website at https://ric-carl.herokuapp.com/ "
          command: |
            echo "Deploying to Heroku, via git, Deployment defined in the Heroku.yml"
            echo "Checking Circle CI Job env. variables"
            echo "SECRETHUB_ORG=[${SECRETHUB_ORG}]"
            echo "SECRETHUB_REPO=[${SECRETHUB_REPO}]"
            echo "HEROKU_APP_ID=[${HEROKU_APP_ID}]"
            export HEROKU_API_KEY=$(secrethub read "${SECRETHUB_ORG}/${SECRETHUB_REPO}/carlbot/heroku/api-token")
            export REPO_HEROKU=https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_ID}.git
            git remote remove heroku
            git remote add heroku ${REPO_HEROKU}
            git push -u heroku master:main
            # && git push -u heroku --tags
            echo "Run this to see the logs of the Heroku deployment: "
            echo "heroku logs --tail --app ${HEROKU_APP_ID}"
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - container_images_publish:
          context: riccarl-cicd
          filters:
            branches:
              ignore:
                - master
                - develop
                - /^feature*/
                - /^support*/
                - /^bugfix*/
                - /^hotfix*/
                - /^release*/
            tags:
              # only: /^v.*/
              only:
                - /^[0-999].[0-999].[0-999]/
                - /^[0-999].[0-999].[0-999]-alpha/
                - /^[0-999].[0-999].[0-999]-beta/
      - deploy_to_heroku:
          context: riccarl-cicd
          requires:
            - container_images_publish
          filters:
            branches:
              ignore:
                - master
                - develop
                - /^feature*/
                - /^support*/
                - /^bugfix*/
                - /^hotfix*/
                - /^releases*/
            tags:
              # only: /^v.*/
              only:
                - /^[0-999].[0-999].[0-999]/
                - /^[0-999].[0-999].[0-999]-alpha/
                - /^[0-999].[0-999].[0-999]-beta/
